openwisp/netjsonconfig

docs/source/general/basics.rst

References #62 
Please let me know if any changes needs to be made. :)

Added doc on template ordering

---

docs/source/backends/openwrt.rst
docs/source/general/basics.rst
netjsonconfig/backends/openwrt/renderers.py
tests/openwisp/test_backend.py
tests/openwrt/test_system.py

Added zonename attribute

---

bin/netjsonconfig
docs/source/general/commandline_utility.rst
netjsonconfig/exceptions.py
tests/test_bin.py

This pr adds a command to validate the netjson input after it has been merged with templates and such.
As an example, using the NetJSON found [here](http://netjson.org/rfc.html#DeviceConfiguration-example)
```
netjsonconfig -c example.json -b openwrt -m validate --verbose
netjsonconfig: JSON Schema violation
ValidationError {u'name': u'radio0', u'country': u'en', u'disabled': False, u'phy': u'phy0', u'tx_power': 18, u'channel': 149, u'channel_width': 20} is not valid under any of the given schemas {u'name': u'radio0', u'country': u'en', u'disabled': False, u'phy': u'phy0', u'tx_power': 18, u'channel': 149, u'channel_width': 20} is not valid under any of the given schemas
Failed validating 'oneOf' in schema['properties']['radios']['items']:
{'oneOf': [{'$ref': …
```

Validate your input

---

setup.py

[packaging] Added conditional dependencies for wheel

---

netjsonconfig/exceptions.py
tests/test_jsonschema_error.py

An example is wort thousands words
```json
{
"type": "DeviceConfiguration",
"general": {},
"interfaces": [
{
"type": "wireless",
"wireless": {
"radio": "ath0",
"mode": "access_point",
"ssid": "test"
},
"addresses": [
{
"address": "192.168.1.20",
"mask": 24,
"family": "ipv4",
"proto": "static"
}
]
}
]
}
```
Raise validation errors
```
netjsonconfig: JSON Schema violation
ValidationError {u'wireless': {u'radio': u'ath0', u'mode': u'access_point', u'ssid': u'test'}, u'type': u'wireless', u'addresses': [{u'address': u'192.168.1.20', u'mask': 24, u'family': u'ipv4', u'proto': u'static'}]} is not valid under any of the given schemas
Failed validating 'oneOf' in schema['properties']['interfaces']['items']:
{'oneOf': [{'$ref': '#/definitions/network_interface'},
{'$ref': …
```

Travel all the errors in report

---

netjsonconfig/backends/openwrt/converters/interfaces.py
netjsonconfig/backends/openwrt/converters/routes.py
netjsonconfig/backends/openwrt/converters/rules.py

For some strange reason this bug popped out of the blue.
Apparently arguments passed to the ipaddress library must be unicode strings.
No idea why this didn't come up earlier.
Closes #97

[python2] Fixed py2-ipaddress related unicode bug

---

bin/netjsonconfig
docs/source/backends/create_your_backend.rst
docs/source/index.rst
netjsonconfig/__init__.py
netjsonconfig/backends/openwrt/schema.py

Hi all,
this will solve a problem that I had last summer during GSOC. Using `entry_points` in the definition
of `setup.py` we can query possible backends for use in netjsonconfig in other packages instead of having long-lived branches.
This is an example for a `setup.py` using the `entry_points` directive
```python
from setuptools import setup, find_packages                                                                                                           
setup(                                                                                                                                                
name='airos',                                                                                                                                  
version='0.0.0', …
```

query backends from installed packages

---

bin/netjsonconfig

Every other error from the netjson library has a custom error reporting but when I am working on a new feature it's easy to mess things up and I wuold like to know what and why.
This PR should print the full traceback for error others than ValidationError when I use the verbose flag.
This should get rid of the "remove the last exception handling lines" during development

wip: print full traceback when verbose

---

docs/source/backends/create_your_backend.rst

last release introduced the feature of querying for available backends at runtime, the documentation
page was correct on how to create a plugin for a backend but did not explain how to use one

WIP:  how to use backends from plugins

---

netjsonconfig/backends/openwrt/converters/interfaces.py
tests/openwrt/test_interfaces.py

This Issue is in reference to the issue #118 . It would be great to have your views on the changes made.
Thank you in advance. 
Closes #118

GCI Task: [netjsonconfig] TypeError: can only concatenate list (not "str") to list

---

requirements-test.txt

Install `flake8` and `isort` via `openwisp-utils[qa]`.

[qa] Install flake8 and isort via openwisp-utils[qa]

---

docs/source/general/setup.rst

Change dirve to drive in the "Install development version" section

[docs] Fix typo in setup.rst

---

netjsonconfig/backends/openvpn/openvpn.py
netjsonconfig/schema.py
tests/openvpn/test_backend.py
tests/openwisp/test_backend.py

OpenVPN certificate files will have `0600` default permission.
Modified tests for same.
Related https://github.com/openwisp/django-netjsonconfig/issues/169
Closes #147

[x509] Added dedicated file mode for generated x509 certificates #147

---

netjsonconfig/backends/base/converter.py
tests/openwrt/test_network.py

I found that the issue #104 is because the order of the list items is causing problems, `switch_vlan` is defined and processed before `switch` which is causing `KeyError` as switch itself is not existing at the time `switch_vlan` is being processed.
This pull request solves the problem by reordering the intermediate list.
Closes #104
Please let me know if there is a better way to solve this issue!

[bug] Fix switch vlan ordering #104

---

netjsonconfig/backends/base/backend.py
tests/openwrt/test_backend.py

If a file is present in multiple places (templates, configuration)
The last definition wins.
eg:
- the configuration overrides the template
- the second template overrides the first

[fix] Deduplicate files

---

netjsonconfig/backends/base/backend.py

Fix minor typo in raise TypeError https://github.com/openwisp/netjsonconfig/issues/151

[typo] Fix minor typo in raise TypeError

---

.gitignore
netjsonconfig/backends/base/backend.py
netjsonconfig/backends/openwrt/schema.py
tests/openwrt/test_network.py

Fixed the issue by adding a pattern to match the valid src and dest notation.
Fixes #96

[fix] Openwrt backend validation problem for property ip_rules/src #96

---

CHANGES.rst
docs/source/backends/openwrt.rst
netjsonconfig/backends/openwrt/converters/interfaces.py
netjsonconfig/backends/openwrt/schema.py
tests/openwrt/test_dialup.py
tests/openwrt/test_interfaces.py

These are useful for protocols like ppp, pppoe, pppoa, etc.:
https://wiki.openwrt.org/doc/uci/network#protocol_ppp_ppp_over_modem

[feature] Add options username and password to interface settings in the OpenWRT backend

---

netjsonconfig/schema.py

Corrected the notation because it was showing ```EAP-PEAP``` even though ```TTLS``` was set for ```OpenWrt```.
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

[openwrt] Fix the EAP protocol notation

---

netjsonconfig/backends/openwrt/converters/wireless.py
netjsonconfig/schema.py
tests/openwrt/test_encryption.py

This patch is tested on these.
- ```OpenWrt```: latest (```4b587f25614f3f7215360f96807ce760fa4ef3aa```)
- hardware: TP-Link Archer C6 v2
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>

[openwrt] Add support for WPA3-Personal

---

docs/source/conf.py

ReadTheDocs build was failing because latex does not
support nested tables that is used in backends/wireguard.rst
Closes https://github.com/openwisp/netjsonconfig/issues/211

[chores] Fixed ReadTheDocs build

---

.readthedocs.yml

[chores] Added ReadTheDocs configuration #211

---

netjsonconfig/channels.py

- 36 to 64, increments of 4 (U-NII-1 + U-NII-2A), as is
- 100 to 144, increments of 4 (U-NII-2C), instead of up to 140
- 149 to 177, increments of 4 (U-NII-3 + U-NII-4), entirely missing
#233

Add missing WiFi 5GHz / 802.11ac channels on U-NII-2C and U-NII-3 (Closes #233)

---

netjsonconfig/backends/openvpn/openvpn.py
tests/openvpn/test_backend.py

The client configuration generated by OpenVpn.autoclient will have "script_security" set to "2" and "log" set to "/var/log/<ifname>.log".
Closes #240

[change] Updated default values for parameters OpenVpn.auto_client #240

---

netjsonconfig/backends/openwrt/converters/wireless.py
tests/openwrt/test_wireless.py

- Removed `str.lstrip()` for getting `bridge_name` since the **lstrip()** arguments are not a prefix; rather, all combinations of their values are stripped that results in incorrect name.
Ref : https://docs.python.org/3/library/stdtypes.html#str.lstrip
Fixes #249

[fix] Fixed wrong network name in wireless interface #249

---

netjsonconfig/utils.py
tests/test_utils.py

In some cases it's possible that a list may be used as the key of a dictionary, which would raise an exception because python lists are not hashable. Therefore, when this happens, we need to convert the list to tuple, which can be hashed.

[fix] Fixed unashable type list error in merge_list

---

netjsonconfig/backends/openwrt/converters/wireless.py
tests/openwrt/test_wireless.py

If WiFI roaming (802.11r) is not enabled, do not generate the UCI config options in the wireless configuration.

[change] OpenWrt: hide roaming UCI if roaming disabled

---

netjsonconfig/schema.py
tests/openwrt/test_encryption.py

Closes #264
@pandafy this change here looks like a mistake, which I am fixing in this PR:
https://github.com/openwisp/netjsonconfig/commit/e696759a#diff-83e7f712c7b8a94dcf6a0acb84af4a1566db59ada5e3ecae57ab6f487ec93bd0L483-L485
The "optional" option was removed but  the corresponding "enum_titles" was not. However, the section in the schema is named "encryption_mfp_property_optional" so it doesn't make a lot of sense to remove the possibility of setting MFP to "optional".
Let me know if you think that was not a mistake and give us more explanation.

[fix] Fixed optional management frame protection #264

---

.github/workflows/ci.yml
README.rst
docs/source/backends/vpn.rst
docs/source/backends/zerotier.rst
docs/source/general/basics.rst
netjsonconfig/__init__.py
netjsonconfig/backends/base/backend.py
netjsonconfig/backends/zerotier/converters.py
netjsonconfig/backends/zerotier/parser.py
netjsonconfig/backends/zerotier/renderer.py
netjsonconfig/backends/zerotier/schema.py
netjsonconfig/backends/zerotier/templates/zerotier.jinja2
netjsonconfig/backends/zerotier/zerotier.py
tests/zerotier/test_backend.py
tests/zerotier/test_parser.py

1. Install [Zerotier](https://www.zerotier.com/download/)
2. Install [Ztncui - Web Interface](https://key-networks.com/ztncui/)
3. Get your Zerotier Service API token `sudo cat /var/lib/zerotier-one/authtoken.secret`
- **Prototype Branch**:  https://github.com/openwisp/openwisp-controller/tree/zerotier-prototype
https://github.com/openwisp/netjsonconfig/assets/56113566/5787c6a8-1cd0-4d00-8d7c-a118252bed60
**Todos**
Closes #208

[feature] Added ZeroTier backend #208

---

netjsonconfig/backends/zerotier/schema.py

There are certain properties in the ZeroTier schema that require default values. For example, if we don't provide a default value for the `multicastLimit` property, it will be set to `0` during an API call, which disables IPv4 communication for the network.
_**Note:** This update will resolve the **SSH/ping** issues we encountered during the last weekly meeting in the demo_

[change] Added the required default values to the ZeroTier schema

---

docs/source/backends/zerotier.rst
netjsonconfig/backends/openwrt/converters/zerotier.py
netjsonconfig/backends/openwrt/openwrt.py
netjsonconfig/backends/openwrt/schema.py
netjsonconfig/backends/zerotier/zerotier.py
tests/openwrt/test_backend.py
tests/openwrt/test_zerotier.py
tests/zerotier/test_backend.py

[feature] Added support for custom zt ifname #284 

---

README.rst
docs/source/backends/vpn.rst
docs/source/backends/zerotier.rst
docs/source/general/basics.rst
netjsonconfig/__init__.py
netjsonconfig/backends/base/backend.py
netjsonconfig/backends/openwrt/converters/__init__.py
netjsonconfig/backends/openwrt/converters/zerotier.py
netjsonconfig/backends/openwrt/openwrt.py
netjsonconfig/backends/openwrt/schema.py
netjsonconfig/backends/zerotier/converters.py
netjsonconfig/backends/zerotier/parser.py
netjsonconfig/backends/zerotier/renderer.py
netjsonconfig/backends/zerotier/schema.py
netjsonconfig/backends/zerotier/templates/zerotier.jinja2
netjsonconfig/backends/zerotier/zerotier.py
tests/openwrt/test_backend.py
tests/openwrt/test_zerotier.py
tests/zerotier/test_backend.py
tests/zerotier/test_parser.py

[feature:gsoc23] Zerotier support on OpenWrt

---

netjsonconfig/backends/openwrt/converters/wireless.py
netjsonconfig/backends/openwrt/schema.py
tests/openwrt/test_encryption.py

- Generate "auth_sever", "auth_port" and "auth_secret" options from "server", "port" and "key" properties
- Set "acct_secret" to the value of "key" if it is not configured in NetJSON
- Add new options: "acct_inverval", "dae_client", "dae_port", "dae_secret"
Closes #291

[change] OpenWrt: updated WPA enterprise settings #291

---

netjsonconfig/backends/wireguard/converters.py
tests/wireguard/test_backend.py

In one case I experienced the MTU not being set to the expected default of 1280. Including the default values in the configuration can't hurt.

[change] Wireguard: do not remove default options

---

docs/source/backends/wireguard.rst
netjsonconfig/backends/wireguard/schema.py

[docs] Added all supported paramenters of WireGuard backend #297

---

docs/source/backends/openwrt.rst
netjsonconfig/backends/openwrt/converters/interfaces.py
netjsonconfig/backends/openwrt/converters/wireless.py
tests/openwrt/test_backend.py
tests/openwrt/test_interfaces_dsa.py
tests/openwrt/test_wireless.py
tests/openwrt/test_wireless_legacy.py

Fixes #314.
If the wireless interface has any address defined, attach it automatically to the related network interface.

[fix] Fixed automatic attachment of wireless interface to network interface #314

---

docs/source/backends/openwrt.rst
netjsonconfig/backends/openwrt/converters/interfaces.py
netjsonconfig/backends/openwrt/schema.py
tests/openwrt/test_modemmanager_dsa.py

[fix] Removed device configuration block for modemmanager interface #316

---

docs/source/backends/zerotier.rst
netjsonconfig/backends/openwrt/converters/zerotier.py
netjsonconfig/backends/openwrt/schema.py
netjsonconfig/backends/zerotier/converters.py
netjsonconfig/backends/zerotier/schema.py
netjsonconfig/backends/zerotier/zerotier.py
tests/openwrt/test_zerotier.py
tests/zerotier/test_backend.py

[feature] Added support for ZeroTier > 1.14 #312

---

netjsonconfig/backends/openwrt/schema.py
netjsonconfig/backends/zerotier/schema.py

The description for `allow_managed` setting was interpreted as an array instead of a string.

[fix] Fixed ZeroTier schema for allow_managed field

---

.github/workflows/version-branch.yml
CHANGES.rst
netjsonconfig/version.py
requirements-test.txt

[ci] Added GitHub workflow to replicate commits to version branch

---

setup.py

Without this fix, the package will not upload to PyPI. 
`twine upload dist/*` gives the following error 
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                        
'Development Status :: 5 - Production/Stable ' is not a valid classifier. See                                          
https://packaging.python.org/specifications/core-metadata for more information. 
```
Moreover, the PyPI CI task was not triggered for 1.1.1 release.

[fix] Fixed development status in setup.py

---

docs/source/backends/zerotier.rst
netjsonconfig/backends/zerotier/zerotier.py
tests/openwrt/test_backend.py
tests/openwrt/test_zerotier.py
tests/zerotier/test_backend.py

The configuration format has changed on OpenWrt since ZeroTier 1.14.0. Previously, it supported running multiple services of the ZeroTier controller, but now only one service is allowed called "global".
Hence, the default name is changed from "ow_zt" to "global".

[fix] Update ZeroTier default name from 'ow_zt' to 'global'
