netjsonconfig/backends/openwrt/renderers.py, netjsonconfig/backends/openwrt/schema.py, tests/openwrt/test_netjson.py, tests/openwrt/test_radio.py
Improved NetJSON compatibility, references and fixes #73.
=> Improved NetJSON compatibility

netjsonconfig/backends/openwrt/converters.py
=> [qa] Isort Fix

README.rst, docs/source/index.rst
For GCI Task: https://codein.withgoogle.com/tasks/5685705210593280/
=> Added Gitter badges to README.rst and docs/source/index.rst

netjsonconfig/backends/openwrt/converters/wireless.py, tests/openwrt/test_encryption.py
=> [openwrt-wireless] Made "encryption none" explicit

.travis.yml, requirements-test.txt
Added commit message style check
=> [qa] Added commit message style check

.gitignore, .travis.yml, docs/source/general/contributing.rst, docs/source/general/running_tests.rst, requirements-test.txt, runtests.py, setup.py
Shifted tests to nose2 from nose.
Fixes #137
=> [tests] Migrate tests to nose2 #137

README.rst
Fixed grammatical error to make it more readable.
=> Updated Readme.md

.travis.yml, bin/netjsonconfig, netjsonconfig/backends/base/backend.py, netjsonconfig/backends/base/parser.py, netjsonconfig/backends/openwisp/openwisp.py, netjsonconfig/backends/openwrt/converters/interfaces.py, netjsonconfig/backends/openwrt/converters/openvpn.py, netjsonconfig/backends/openwrt/converters/routes.py, netjsonconfig/backends/openwrt/converters/rules.py, netjsonconfig/backends/openwrt/converters/switch.py, netjsonconfig/utils.py, setup.py
* Simplified super() function
* removed 2.7 from travis
* added 3.7 in travis
Fixes #140
=> [dependencies] Drop support for python2 #140

tests/openvpn/test_backend.py
=> [tests] Ensure ip is valid remote in OpenVPN backend #132

CHANGES.rst, docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/interfaces.py, netjsonconfig/backends/openwrt/schema.py, tests/openwrt/test_interfaces.py, tests/openwrt/test_modemmanager.py
Added support for modem manager interfaces (2G/3G/4G).
=> [feature] Add support for modem manager interfaces 

docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/interfaces.py, netjsonconfig/backends/openwrt/schema.py, tests/openwrt/test_interfaces.py
=> [chores] Minor improvements to dialup interface schema #168

requirements.txt
Closes #189
Tested with `openwisp-controller`, Jinja2~=3.0.0
=> [deps] Upgrade to Jinja 3.0 #189

docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/radios.py, netjsonconfig/backends/openwrt/schema.py, netjsonconfig/schema.py, tests/openwrt/test_radio.py
Follow up ofhttps://github.com/openwisp/netjsonconfig/pull/202.
=> [feature] WiFi 6

docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/radios.py, netjsonconfig/backends/openwrt/schema.py, netjsonconfig/schema.py, tests/openwrt/test_netjson.py, tests/openwrt/test_radio.py
=> [fix] Removed option of 2.4GHz radio for 802.11ac #190

netjsonconfig/schema.py, tests/openvpn/test_parser.py
=> [Fix] File path shouldn't be allowed to be empty #166

docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/wireless.py, netjsonconfig/backends/openwrt/openwrt.py, tests/openwrt/test_wireless.py
=> [change] Added automatic addition of networks in wireless interfaces #191

netjsonconfig/utils.py, tests/openvpn/test_backend.py, tests/test_utils.py
=> [Fix] Multiple templates defining the same additional file generate conflicts #197

docs/source/backends/openwrt.rst, netjsonconfig/backends/openwrt/converters/interfaces.py, netjsonconfig/backends/openwrt/schema.py, tests/openwrt/test_modemmanager_dsa.py, tests/openwrt/test_modemmanager_legacy.py
=> [fix] Fixed modem-manager configuration for OpenWrt 21 #228

netjsonconfig/backends/openwrt/converters/interfaces.py, tests/openwrt/test_interfaces_dsa.py
=> [fix] Fixed bridges renamed on OpenWrt 21 #243

CHANGES.rst, netjsonconfig/version.py
=> 1.0.2 release

CHANGES.rst, netjsonconfig/version.py
=> [docs] Added changelog for 1.0.2 release

netjsonconfig/schema.py, tests/openwrt/test_encryption.py
=> [feature] Added wpa3-personal encryption for 802.11s mesh #254

netjsonconfig/backends/openwrt/converters/wireless.py, netjsonconfig/schema.py, tests/openwrt/test_encryption.py
Related to : https://github.com/openwisp/netjsonconfig/pull/251
Closes #193
=> [feature] Add OWE encryption type

netjsonconfig/backends/openwrt/converters/wireguard_peers.py, tests/openwrt/test_wireguard.py
=> [fix] Fixed multiple wireguard peers bug #253

netjsonconfig/backends/wireguard/converters.py, netjsonconfig/backends/wireguard/schema.py, tests/wireguard/test_backend.py
=> [feature] Added properties to wireguard schema #280

netjsonconfig/backends/openwrt/converters/routes.py, tests/openwrt/test_network.py
=> [fix] Fixed parsing route without gateway #290

README.rst, docs/source/general/running_tests.rst, docs/source/index.rst, netjsonconfig/__init__.py
- minor docs updates and improvements
- removed usage of deprecated `pkg_resources` lib
=> [misc] Minor improvements

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> [feature] Issue and pull request template added  #305

docs/source/backends/openvpn.rst, docs/source/backends/openwisp.rst, docs/source/backends/openwrt.rst, docs/source/backends/wireguard.rst, docs/source/backends/zerotier.rst, docs/source/general/commandline_utility.rst, docs/source/general/goals.rst, docs/source/index.rst
=> [docs] OpenWRT => OpenWrt, removed LEDE

netjsonconfig/backends/openwrt/converters/openvpn.py, tests/openwrt/test_openvpn.py
=> [fix:openwrt] Remove fragment option from OpenVPN config when set to 0 #321

.github/workflows/version-branch.yml
=> [ci] Fixed the module name for the version-branch action

.github/workflows/version-branch.yml
=> [ci] Fixed replicate commit workflow

CHANGES.rst, netjsonconfig/version.py
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 1.1.1 release

netjsonconfig/version.py
=> [chores] Fixed version number to 1.2.0a

docs/source/backends/zerotier.rst, netjsonconfig/backends/openwrt/converters/zerotier.py, tests/openwrt/test_zerotier.py, tests/zerotier/test_backend.py
=> [fix] Fixed typo in fields of ZeroTier backend #342

.github/workflows/ci.yml, netjsonconfig/backends/base/backend.py, netjsonconfig/backends/openvpn/parser.py, netjsonconfig/backends/openwrt/parser.py, netjsonconfig/backends/openwrt/schema.py, netjsonconfig/backends/wireguard/parser.py, netjsonconfig/backends/zerotier/parser.py, tests/openvpn/test_parser.py, tests/openwrt/test_backend.py, tests/openwrt/test_network.py, tests/openwrt/test_parser.py, tests/zerotier/test_parser.py
Closes #345
Removed:
- Support for Python < 3.9
Added:
-  support for Python 3.11, 3.12 & 3.13
=> [deps] Add support for Python >=3.12, 3.14

CHANGES.rst
GitHub release: https://github.com/openwisp/netjsonconfig/releases/tag/1.1.3
PyPI release: https://pypi.org/project/netjsonconfig/1.1.3/
=> [docs] Added changelog for 1.1.3 release
